### ISSUE TITLE
How to decorate Devise's current_user ?

### ISSUE THREAD

**Issue by zedtux** [amatsuda/active_decorator#98]
First of all, thank you very much for this nice gem ! 👍 

Like 99% Rails projets I'm using devise in order to manage users and I'd like to decorate the `current_user` object from Devise and I'm wondering what would be the best way to do it?

As of now, based on [this blog article](https://www.devroom.io/2012/04/14/decorating-devise-s-current_user-with-draper/) and [this issue](https://github.com/amatsuda/active_decorator/issues/91) I've added the following to my `ApplicationController` :

```ruby
class ApplicationController < ActionController::Base
  # ...

  def current_user
    ActiveDecorator::Decorator.instance.decorate(super) unless super.nil?
  end
end
```

This works just fine.

**Comment by amatsuda** [comment]
Wow, I wasn't aware that I'm a 1% Rails developer...
Anyway, that indeed seems like the best way to simply implement what you need.

As trivial nitpicks,
- generally, it'd be better to avoid calling the same `super` method twice here. You can use a lvar, e.g.)
```
    (u = super) && ActiveDecorator::Decorator.instance.decorate(u)
```

- I'd define the `current_user` method as a private method since it's not an [action_method](https://github.com/rails/rails/blob/826e34be/actionpack/lib/abstract_controller/base.rb#L66-L87) (don't ask me why Devise doesn't do so)

**Comment by zedtux** [comment]
Thank you @amatsuda for your comment !
